---
address_id: 12345
smartlock_id: 12345
nuki_api_token: token
telegram_bot:
  enabled: true
  sender_name: telegram
senders:
  - name: telegram
    telegram:
      token: token
      chat_id: 12345
      include_date: true
      timezone: Europe/Paris
  - name: console
    console:
      include_date: true
